# Generated by Django 3.0 on 2020-12-04 03:38

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_pics', models.ImageField(default='default.png', upload_to='users/%Y/%m/%d/')),
                ('bio', ckeditor.fields.RichTextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999'. Up to 15 digits allowed.", regex='^\\+\\d*$')])),
                ('twitter_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('github_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('codepen_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
