# Generated by Django 2.2.8 on 2019-12-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191205_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
