# Generated by Django 2.2.8 on 2019-12-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191205_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dribble_url',
            new_name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube_url',
        ),
    ]
