# Generated by Django 2.2.8 on 2019-12-05 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191205_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999'. Up to 15 digits allowed.", regex='^\\+(\\d{9-15})(?:\\s|$)')]),
        ),
    ]
