# Generated by Django 3.0 on 2019-12-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_testimonial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='passion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
