# Generated by Django 3.0 on 2019-12-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_introduction_passion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='intro',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='recommender_pic',
            field=models.ImageField(default='user-01.jpg', upload_to='recommenders_pics'),
        ),
    ]
